<?php
	$this->headTitle('Aide & Réglement - Challenge de Jolia');
?>
<div class="concours_title">
	<h1>AIDE / HELP</h1>
</div>
<div class="row" style="margin-left:0!important;margin-right:0!important!;">
	<div class="col-xs-12 col-md-10 col-md-offset-2">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#fr">FR</a></li>
			<li><a data-toggle="tab" href="#en">EN</a></li>
		</ul>
	</div>
	<div class="hidden-xs hidden-sm col-md-2">
		<img src="//jolstatic.fr/dofus/Modules/Challenge/main/jolia_challenge.png" class="img-responsive" alt=""/>
	</div>

	<div class="col-xs-12 col-md-10 description_challenge">
		<div class="tab-content">
			<div id="fr" class="tab-pane fade in active">
				<h2>Participer</h2>
				<p>
					Afin de prendre part à un concours, vous aurez tout d'abord besoin de <strong>créer un compte sur JeuxOnline ou de vous connecter avec un compte que vous possédez déjà</strong>. Cela nous est essentiel afin d'assigner un pseudo à une participation, et pouvoir vous contacter en cas de besoin pour la réception de vos cadeaux si vous atteignez le podium du concours.
				</p>
				<p>
					Afin de rejoindre un concours, <strong>cliquez sur "> PARTICIPER <"</strong> présent sur le menu principal du Challenge de Jolia. Vous y trouverez alors l'ensemble des concours disponibles ou passés. <strong>Les concours en cours ou à venir s'afficheront automatiquement en haut de tableau</strong>, vous ne pourrez pas les louper.
				</p>
				<br>
				<a href="//jolstatic.fr/dofus/Modules/Challenge/main/help/participer.png" class="fancybox"><img class="img-thumbnail" width="60%" src="//jolstatic.fr/dofus/Modules/Challenge/main/help/participer.png" style="margin: auto auto;display:block;"/></a>
				<br><br>
				<p>
					A partir de cette page vous pourrez vous rendre sur celle dédiée au concours pour y <strong>découvrir son réglement, ses lots et son thème</strong>. Les pages du Challenge de Jolia sont composées d'onglets, vous pouvez donc <strong>naviguer entre les onglets présents sur une même page pour y découvrir des informations différentes</strong>.
				</p>
				<h2>Envoyer sa participation</h2>
				<p>
					Une fois les Informations Générales du concours connues, vous pouvez <strong>envoyer votre participation en accord avec le thème imposé</strong>. <strong>Important :</strong> une participation envoyée ne peut pas être annulée, faites donc très attention à ce que vous souhaitez partager. En cas d'erreur importante (mauvais choix d'image), vous pouvez <a href="https://forums.jeuxonline.info/private.php?do=newpm&u=412805">nous contacter</a> pour que nous annulions votre participation. Cela vous permettra de concourir à nouveau.
				</p>
				<br>
				<a href="//jolstatic.fr/dofus/Modules/Challenge/main/help/envoyer_participation.jpg" class="fancybox"><img class="img-thumbnail" width="60%" src="//jolstatic.fr/dofus/Modules/Challenge/main/help/envoyer_participation.jpg" style="margin: auto auto;display:block;"/></a>
				<br><br>
				<p>
					Vous avez également la possibilité d'ajouter une description à votre image, si une histoire doit être racontée ou si vous souhaitez décrire un élément pouvant paraître abstrait. Cette étape n'est pas obligatoire, laissez le champ libre si nécessaire.
				</p>
				<p>
					Une fois votre participation envoyée, celle-ci est disponible dans l'onglet Participer de la page du concours, accompagnée de son éventuelle description.
				</p>
				<br>
				<a href="//jolstatic.fr/dofus/Modules/Challenge/main/help/envoyer_participation2.jpg" class="fancybox"><img class="img-thumbnail" width="60%" src="//jolstatic.fr/dofus/Modules/Challenge/main/help/envoyer_participation2.jpg" style="margin: auto auto;display:block;"/></a>
				<br><br>
				<p>
					<strong>Si les spécificités du concours le permettent, vous pourrez consulter les participations des autres joueurs dans l'onglet "Voir les participations"</strong>. Mais dans la grande majorité des concours, elles ne seront pas visibles pour éviter d'éventuelles copies ou "stratégies" pour être certain de faire mieux que les participations déjà présentées.
				</p>
				<h2>Résultats</h2>
				<p>
					Une fois la date de fin d'un concours passée, <strong>une semaine d'attente sera automatiquement activée et sera dédiée aux votes du jury du concours</strong>. <strong>Ce jury est constitué des membres de l'équipe JeuxOnline - DOFUS et de possibles invités qui changeront d'une édition à l'autre</strong>. Ceux-ci auront alors la lourde tâche d'attribuer une note à votre participation. Celle-ci s'étend de 0 à 5, et <strong>une moyenne sera finalement effectuée entre ces différentes notes pour vous classer</strong>.
				</p>
				<br>
				<a href="//jolstatic.fr/dofus/Modules/Challenge/main/help/concours_termine.jpg" class="fancybox"><img class="img-thumbnail" width="60%" src="//jolstatic.fr/dofus/Modules/Challenge/main/help/concours_termine.jpg" style="margin: auto auto;display:block;"/></a>
				<br><br>
				<p>
					<strong>Les résultats d'un concours seront automatiquement rendus disponibles à J+7 de la date de fin de la phase de participation</strong>. Vous n'aurez qu'à consulter la page du concours à cet instant pour découvrir les résultats. <strong>Seul le classement des trois premiers joueurs vous sera donné</strong>, permettant d'indiquer un podium. Toutes les autres participations seront classées aléatoirement pour être visibles de tous.
				</p>
				<h2>Gains</h2>
				<p>
					<strong>Les joueurs qui atteindront le podium d'un concours pourront repartir avec des lots en jeu</strong>. Ces récompenses vous sont <strong>offertes par l'équipe DOFUS qui a une nouvelle fois accepté de soutenir l'événement</strong> et celles-ci changeront à chaque édition du concours. Nous pourrions vous les dévoiler dès maintenant, mais <strong>nous préférons garder la surprise</strong> ! Toutefois, n'ayez pas peur, <strong>les récompenses seront toujours indiquées dans le réglement de chaque concours</strong>. Vous saurez ainsi pour quels objets vous participez, en plus des Points du Chasseur vous permettant d'obtenir le Bouclier du Chasseur de Trooll.
				</p>
				<h2>Important !</h2>
				<p>
					<strong>Afin de recevoir vos gains directement sur votre compte, nous vous demandons de bien vouloir compléter votre PROFIL JEUXONLINE - DOFUS</strong>, celui-ci est accessible depuis la page de participation de chaque concours via l'onglet "Mes Infos". <strong>Nous vous demandons alors d'y inscrire votre PSEUDO PUBLIC DE COMPTE ANKAMA</strong> <em>(celui qui apparaît sur les forums Ankama et sur utilisation de la commande "/whois Pseudo" en jeu)</em>. Cela nous permettra de <strong>transmettre ces informations à l'équipe DOFUS qui se chargera du crédit de vos gains</strong> dans les délais les plus brefs.
				</p>
				<p>
					Pour toute question supplémentaire, n'hésitez pas à nous contacter ou réagir sur le sujet forum dédié au concours !
				</p>
				<br>
				<a href="//jolstatic.fr/dofus/Modules/Challenge/main/help/infos_persos.jpg" class="fancybox"><img class="img-thumbnail" width="60%" src="//jolstatic.fr/dofus/Modules/Challenge/main/help/infos_persos.jpg" style="margin: auto auto;display:block;"/></a>
				<br><br>
			</div>
			<div id="en" class="tab-pane fade">
				Soon.
			</div>
		</div>
	</div>
</div>