<?php

$title = 'Challenge de Jolia';
$this->headTitle($title);

?>
<div class="concours_title">
	<h1>LE CHALLENGE DE JOLIA</h1>
</div>
<div class="row" style="margin-left:0!important;margin-right:0!important!;">
	<div class="col-xs-12 col-md-10 col-md-offset-2">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#fr">FR</a></li>
			<li><a data-toggle="tab" href="#en">EN</a></li>
		</ul>
	</div>
	<div class="hidden-xs hidden-sm col-md-2">
		<img src="//jolstatic.fr/dofus/Modules/Challenge/main/jolia_challenge.png" class="img-responsive" alt=""/>
	</div>

	<div class="col-xs-12 col-md-10 description_challenge">
		<div class="tab-content">
			<div id="fr" class="tab-pane fade in active">
				<p><strong>Le Challenge de Jolia est un concours artistique mensuel proposé aux joueurs de DOFUS PC & DOFUS TOUCH.</strong></p>

				<p>Chaque mois, les joueurs sont invités à <strong>produire une oeuvre respectant le thème indiqué par les organisateurs</strong>. Ce thème peut être très libre comme très restrictif et il sera nécessaire de le respecter afin d'espérer obtenir la meilleure place au classement.</p><br>
				<strong>Il existe à ce jour deux types de concours :</strong><br><br>
				<ul>
					<li><strong>Skin</strong> : Les joueurs doivent réaliser un personnage, habillé selon leur convenance (quand cela est possible) en respectant le thème imposé. Il leur est possible d'utiliser les outils en ligne disponibles, dont le <a href="https://www.dofusbook.net/fr/outils/skinator" target="_blank" style="color:#749B40;">Skinator de Dofusbook</a>, notre partenaire. Une capture d'écran réalisée en jeu est également possible, mais vous devrez avoir les objets dans votre inventaire pour réaliser cette capture, rendant le travail inutilement complexe.</li><br>
					<li><strong>Havre Sac</strong> : Les joueurs doivent réaliser une salle de Havre Sac respectant un thème imposé. Certains thèmes précis (liés à Nowel par exemple), pourraient désavantager les joueurs qui ne disposent pas de thèmes liés à cet événement. Nous vous conseillons donc fortement de réaliser ceci sur les serveurs BETA TEST, où l'ensemble des thèmes et objets de Havre Sac sont à votre disposition.</li>
				</ul><br>
				<p>
					Les participations sont ensuite classées suivant un <strong>système de notation classique</strong> allant de 0 à 5 points. <strong>Une moyenne est effectuée entre l'ensemble des notes données par les membres du jury afin de déterminer le classement final.</strong>
				</p>
				<p>
					<strong>Les joueurs qui arriveront sur le podium repartiront avec des lots numériques, sur le jeu associé au concours organisé</strong>. Si le concours est proposé à DOFUS PC & DOFUS TOUCH en même temps, le joueur sera libre de choisir sur quel jeu il souhaite recevoir ses récompenses <em>(qui peuvent différer selon le jeu, tout sera précisé dans le réglement de chaque concours)</em>.
				</p>
				<img src="https://jolstatic.fr/www/captures/93/8/121568.png" style="display:block;margin:auto;width:100px;"/>
				<p>
					JeuxOnline - DOFUS permet également aux joueurs de DOFUS PC d'<strong>obtenir un exemplaire du Bouclier du Chasseur de Trooll</strong>, objet d'apparat exclusif lié à notre section vous permettant également d'obtenir un Titre exclusif.
				</p>
				<p>
					<strong>Son obtention s'effectue sur demande d'un joueur si celui-ci a cumulé 6 Points du Chasseur</strong> en participant au Challenge de Jolia.
				</p>
				<p>
					<strong>Une place sur le podium vous assure d'obtenir des Points du Chasseur de la manière suivante :</strong>
				</p>
				<ul>
					<li><strong>1<sup>ère</sup> Place :</strong> 4 Points du Chasseur</li>
					<li><strong>2<sup>nde</sup> Place :</strong> 3 Points du Chasseur</li>
					<li><strong>3<sup>ème</sup> Place :</strong> 2 Points du Chasseur</li>
				</ul>
				<p>
					Un récapitulatif global des gagnants est <a href="https://forums.jeuxonline.info/showthread.php?t=1369617" target="_blank" style="color:#749B40;"><strong>disponible sur nos forums</strong></a>. Ce module ayant été réalisé en décembre 2018, les anciennes éditions du concours n'y sont pas disponibles directement, elles seront ajoutées progressivement dans le futur.
				</p>
			</div>
			<div id="en" class="tab-pane fade">
				<p><strong>Jolia's Challenge is a monthly art contest for DOFUS PC & DOFUS TOUCH players.</strong></p>

				<p>
					Each month, players are invited to <strong>produce a work respecting a theme indicated by the organizers</strong>. This theme can be very free or very restrictive and it will be necessary to respect it in order to obtain the best score.
				</p><br>
				<p>
					<strong>There are two types of contests :</strong>
				</p><br>
				<ul>
					<li><strong>Skin :</strong> Players must realize and dress a character in accordance with the imposed theme. It's possible to use online features, like <a href="https://www.dofusbook.net/fr/outils/skinator" style="color:#749B40;">Dofusbook's Skinator</a>, our partner. A game screenshot is accepted but you need to have items in your inventory to dress your character, it's not very effective.</li><br>
					<li><strong>Haven Bag :</strong> Players must realize a Haven Bag Showroom in accordance with the imposed theme. Some themes may disavantage players who don't have Haven Bag theme in relation with the theme of the contest. For these players, we advise you to create your Haven Bag Showroom on the BETA server. All the themes of the Haven Bag feature are available.</li>
				</ul>
				<p>
					Your work is rated according to a <strong>classical system ranking</strong> from 0 to 5 points. <strong>An average is then done and allows you to classify each other.</strong>
				</p>
				<p>
					<strong>Players who arrive on the podium win digital prizes on the game associated with the contest</strong>. If the contest is linked to DOFUS PC and DOFUS TOUCH at the same time, players will be free to choose on which game he wishes to receive his rewards. <em>(the rewards differ according to the game, check the contest rules for more information)</em>
				</p>
				<img src="https://jolstatic.fr/www/captures/93/8/121568.png" style="display:block;margin:auto;width:100px;"/>
				<p>
					JeuxOnline - DOFUS allows PC players to <strong>get the Trool Hunter's Shield</strong>, a ceremonial item for your shield. <strong>An exclusive title is linked to this item : "Trool Hunter".</strong>
				</p>
				<p>
					<strong>This ceremonial shield can be obtained against 6 Hunter Point</strong> you can get by participating to the Jolia's Challenge.
				</p>
				<p>
					<strong>A place on the final podium guarantee you to get Hunter Points :</strong>
				</p>
				<ul>
					<li><strong>1<sup>rst</sup> Place :</strong> 4 Hunter Points</li>
					<li><strong>2<sup>nd</sup> Place :</strong> 3 Hunter Points</li>
					<li><strong>3<sup>rd</sup> Place :</strong> 2 Hunter Points</li>
				</ul>
				<p>
					You can see, in french, <a href="https://forums.jeuxonline.info/showthread.php?t=1369617" target="_blank" style="color:#749B40;"><strong>on our forums</strong></a> a summary of the previous winners and their points. This contest system was made in December 2018, the old editions of the contest are not directly available, they will be added in the future.
				</p>
			</div>
		</div>
	</div>
</div>